import Head from 'next/head';

import { Accordion, Box, Container, Divider, Link, Text, VStack } from '@chakra-ui/react';

import { List, SectionContent, SectionHeader, SectionItem } from '../components/TnC-PP';
import HeaderLogo from '../components/TnC-PP/HeaderLogo';

const PrivacyPolicy = () => {
  const expandedItems = [...Array.from(Array(30).keys())];

  const renderPrivacyPolicy = () => {
    return (
      <Box pt="1">
        <Accordion defaultIndex={expandedItems} allowMultiple>
          <SectionItem>
            <SectionHeader>Definitions and key terms</SectionHeader>
            <SectionContent>
              To help explain things as clearly as possible in this Privacy
              Policy, every time any of these terms are referenced, are strictly
              defined as:
              <List>
                <li>
                  Cookie: small amount of data generated by a website and saved
                  by your web browser. It is used to identify your browser,
                  provide analytics, and remember information about you such as
                  your language preference or login information.
                </li>
                <li>
                  Company: when this policy mentions “Company,” “we,” “us,” or
                  “our,” it refers to Shopbite.co that is responsible for your
                  information under this Privacy Policy.
                </li>
                <li>
                  Country: where Shopbite.co or the owners/founders of
                  Shopbite.co are based, in this case is Indonesia
                </li>
                <li>
                  Customer: refers to the company, organization or person that
                  signs up to use the Shopbite.co Service to manage the
                  relationships with your consumers or service users.
                </li>
                <li>
                  Device: any internet connected device such as a phone, tablet,
                  computer or any other device that can be used to visit
                  Shopbite.co and use the services.
                </li>
                <li>
                  IP address: Every device connected to the Internet is assigned
                  a number known as an Internet protocol (IP) address. These
                  numbers are usually assigned in geographic blocks. An IP
                  address can often be used to identify the location from which
                  a device is connecting to the Internet.
                </li>
                <li>
                  Personnel: refers to those individuals who are employed by
                  Shopbite.co or are under contract to perform a service on
                  behalf of one of the parties.
                </li>
                <li>
                  Personal Data: any information that directly, indirectly, or
                  in connection with other information — including a personal
                  identification number — allows for the identification or
                  identifiability of a natural person.
                </li>
                <li>
                  Service: refers to the service provided by Shopbite.co as
                  described in the relative terms (if available) and on this
                  platform.
                </li>
                <li>
                  Third-party service: refers to advertisers, contest sponsors,
                  promotional and marketing partners, and others who provide our
                  content or whose products or services we think may interest
                  you.
                </li>
                <li>
                  Website: Shopbite.co."’s" site, which can be accessed via this
                  URL:{' '}
                  <Link href="https://www.shopbite.co" target="_blank">
                    https://www.shopbite.co
                  </Link>
                </li>
                <li>
                  You: a person or entity that is registered with Shopbite.co to
                  use the Services.
                </li>
              </List>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>What Information Do We Collect?</SectionHeader>
            <SectionContent>
              We collect information from you when you visit our website,
              register on our site, place an order, subscribe to our newsletter,
              respond to a survey or fill out a form, interacting with our team
              regarding our services and other actions you make that correspond
              to using or accessing our website.
              <List>
                <li>
                  <Box>
                    <Text fontWeight="bold">
                      Information that we collect automatically
                    </Text>
                    We may automatically collect personal information when you
                    visit our platform, use our services, or participate in our
                    surveys, marketing campaigns, or interact with our staff.
                    This information includes your Internet Protocol (IP)
                    address, device type, unique device identification numbers,
                    geographic location such as country or city, time zone,
                    usage data and other technical information.
                  </Box>
                </li>
                <li>
                  <Box>
                    <Text fontWeight="bold">
                      Information you provide voluntarily
                    </Text>
                    When you sign up to become a Shopbite Users, use or interact
                    with our services or staff, we may ask you to provide
                    personal information voluntarily such as your email address,
                    name, username and hashed password. Furthermore if you wish
                    to subscribe to our paid services, we will also ask for your
                    full name, billing email address, billing address and
                    payment method in order to facilitate billing. You may also
                    provide us with your personal data when you submit a report
                    or contact our staff, when you respond to our surveys and if
                    you participate in our marketing programs.
                  </Box>
                </li>
                <li>
                  <Box>
                    <Text fontWeight="bold">
                      Information from third party sources
                    </Text>
                    We may receive personal information about you from third
                    party sources that we use including service providers that
                    help us operate and provide services to you as well as from
                    third party sources that help us run our marketing
                    campaigns.
                  </Box>
                </li>
              </List>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              How Do We Use The Information We Collect?
            </SectionHeader>
            <SectionContent>
              Any of the information we collect from you may be used in one of
              the following ways:
              <List>
                <li>
                  To personalize your experience (your information helps us to
                  better respond to your individual needs).
                </li>
                <li>
                  To improve our website (we continually strive to improve our
                  website offerings based on the information and feedback we
                  receive from you).
                </li>
                <li>
                  To improve customer service (your information helps us to more
                  effectively respond to your customer service requests and
                  support needs).
                </li>
                <li>To process transactions.</li>
                <li>
                  To administer a contest, promotion, survey or other site
                  feature.
                </li>
                <li>To send periodic emails.</li>
              </List>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>How Long Do We Keep Your Information?</SectionHeader>
            <SectionContent>
              We keep your information only so long as we need it to provide
              Shopbite.co to you and fulfill the purposes described in this
              policy. This is also the case for anyone that we share your
              information with and who carries out services on our behalf. When
              we no longer need to use your information and there is no need for
              us to keep it to comply with our legal or regulatory obligations,
              we’ll either remove it from our systems or depersonalize it so
              that we can't identify you.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>How Do We Protect Your Information?</SectionHeader>
            <SectionContent>
              We implement a variety of security measures to maintain the safety
              of your personal information when you place an order or enter,
              submit, or access your personal information. We offer the use of a
              secure server. All supplied sensitive/credit information is
              transmitted via Secure Socket Layer (SSL) technology and then
              encrypted into our Payment gateway providers database only to be
              accessible by those authorized with special access rights to such
              systems, and are required to keep the information confidential.
              After a transaction, your private information (credit cards,
              social security numbers, financials, etc.) is never kept on file.
              We cannot, however, ensure or warrant the absolute security of any
              information you transmit to Shopbite.co or guarantee that your
              information on the Service may not be accessed, disclosed,
              altered, or destroyed by a breach of any of our physical,
              technical, or managerial safeguards.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Could my information be transferred to other countries?
            </SectionHeader>
            <SectionContent>
              Shopbite.co is incorporated in Indonesia. Information collected
              via our website, through direct interactions with you, or from use
              of our help services may be transferred from time to time to our
              offices or personnel, or to third parties, located throughout the
              world, and may be viewed and hosted anywhere in the world,
              including countries that may not have laws of general
              applicability regulating the use and transfer of such data. To the
              fullest extent allowed by applicable law, by using any of the
              above, you voluntarily consent to the trans-border transfer and
              hosting of such information.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Is the information collected through the Shopbite.co Service
              secure?
            </SectionHeader>
            <SectionContent>
              We take precautions to protect the security of your information.
              We have physical, electronic, and managerial procedures to help
              safeguard, prevent unauthorized access, maintain data security,
              and correctly use your information. However, neither people nor
              security systems are foolproof, including encryption systems. In
              addition, people can commit intentional crimes, make mistakes or
              fail to follow policies. Therefore, while we use reasonable
              efforts to protect your personal information, we cannot guarantee
              its absolute security. If applicable law imposes any
              non-disclaimable duty to protect your personal information, you
              agree that intentional misconduct will be the standards used to
              measure our compliance with that duty.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Can I update or correct my information?
            </SectionHeader>
            <SectionContent>
              <Box>
                The rights you have to request updates or corrections to the
                information Shopbite.co collects depend on your relationship
                with Shopbite.co. Personnel may update or correct their
                information as detailed in our internal company employment
                policies.
              </Box>
              <br />
              <Box>
                Customers have the right to request the restriction of certain
                uses and disclosures of personally identifiable information as
                follows. You can contact us in order to (1) update or correct
                your personally identifiable information, (2) change your
                preferences with respect to communications and other information
                you receive from us, or (3) delete the personally identifiable
                information maintained about you on our systems (subject to the
                following paragraph), by cancelling your account. Such updates,
                corrections, changes and deletions will have no effect on other
                information that we maintain, or information that we have
                provided to third parties in accordance with this Privacy Policy
                prior to such update, correction, change or deletion. To protect
                your privacy and security, we may take reasonable steps (such as
                requesting a unique password) to verify your identity before
                granting you profile access or making corrections. You are
                responsible for maintaining the secrecy of your unique password
                and account information at all times.
              </Box>
              <br />
              <Box>
                You should be aware that it is not technologically possible to
                remove each and every record of the information you have
                provided to us from our system. The need to back up our systems
                to protect information from inadvertent loss means that a copy
                of your information may exist in a non-erasable form that will
                be difficult or impossible for us to locate. Promptly after
                receiving your request, all personal information stored in
                databases we actively use, and other readily searchable media
                will be updated, corrected, changed or deleted, as appropriate,
                as soon as and to the extent reasonably and technically
                practicable.
              </Box>
              <br />
              <Box>
                If you are an end user and wish to update, delete, or receive
                any information we have about you, you may do so by contacting
                the organization of which you are a customer.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Personnel</SectionHeader>
            <SectionContent>
              <Box>
                If you are a Shopbite.co worker or applicant, we collect
                information you voluntarily provide to us. We use the
                information collected for Human Resources purposes in order to
                administer benefits to workers and screen applicants.
              </Box>
              <br />
              <Box>
                You may contact us in order to (1) update or correct your
                information, (2) change your preferences with respect to
                communications and other information you receive from us, or (3)
                receive a record of the information we have relating to you.
                Such updates, corrections, changes and deletions will have no
                effect on other information that we maintain, or information
                that we have provided to third parties in accordance with this
                Privacy Policy prior to such update, correction, change or
                deletion.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Sale of Business</SectionHeader>
            <SectionContent>
              We reserve the right to transfer information to a third party in
              the event of a sale, merger or other transfer of all or
              substantially all of the assets of Shopbite.co or any of its
              Corporate Affiliates (as defined herein), or that portion of
              Shopbite.co or any of its Corporate Affiliates to which the
              Service relates, or in the event that we discontinue our business
              or file a petition or have filed against us a petition in
              bankruptcy, reorganization or similar proceeding, provided that
              the third party agrees to adhere to the terms of this Privacy
              Policy.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Affiliates</SectionHeader>
            <SectionContent>
              We may disclose information (including personal information) about
              you to our Corporate Affiliates. For purposes of this Privacy
              Policy, "Corporate Affiliate" means any person or entity which
              directly or indirectly controls, is controlled by or is under
              common control with Shopbite.co, whether by ownership or
              otherwise. Any information relating to you that we provide to our
              Corporate Affiliates will be treated by those Corporate Affiliates
              in accordance with the terms of this Privacy Policy.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Governing Law</SectionHeader>
            <SectionContent>
              <Box>
                This Privacy Policy is governed by the laws of Indonesia without
                regard to its conflict of laws provision. You consent to the
                exclusive jurisdiction of the courts in connection with any
                action or dispute arising between the parties under or in
                connection with this Privacy Policy except for those individuals
                who may have rights to make claims under Privacy Shield, or the
                Swiss-US framework.{' '}
              </Box>
              <br />
              <Box>
                The laws of Indonesia, excluding its conflicts of law rules,
                shall govern this Agreement and your use of the website. Your
                use of the website may also be subject to other local, state,
                national, or international laws.{' '}
              </Box>
              <br />
              <Box>
                By using Shopbite.co or contacting us directly, you signify your
                acceptance of this Privacy Policy. If you do not agree to this
                Privacy Policy, you should not engage with our website, or use
                our services. Continued use of the website, direct engagement
                with us, or following the posting of changes to this Privacy
                Policy that do not significantly affect the use or disclosure of
                your personal information will mean that you accept those
                changes.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Your Consent</SectionHeader>
            <SectionContent>
              We've updated our Privacy Policy to provide you with complete
              transparency into what is being set when you visit our site and
              how it's being used. By using our website, registering an account,
              or making a purchase, you hereby consent to our Privacy Policy and
              agree to its terms.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Link to Other Websites or Platforms</SectionHeader>
            <SectionContent>
              This Privacy Policy applies only to the Services. The Services may
              contain links to other websites or platforms not operated or
              controlled by Shopbite.co. We are not responsible for the content,
              accuracy or opinions expressed in such websites and platforms, and
              such websites and platforms are not investigated, monitored or
              checked for accuracy or completeness by us. Please remember that
              when you use a link to go from the Services to another website or
              platform, our Privacy Policy is no longer in effect. Your browsing
              and interaction on any other website, including those that have a
              link on our platform, is subject to that website’s own rules and
              policies. Such third parties may use their own cookies or other
              methods to collect information about you.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Cookies</SectionHeader>
            <SectionContent>
              Shopbite.co uses "Cookies" to identify the areas of our website
              that you have visited. A Cookie is a small piece of data stored on
              your computer or mobile device by your web browser. We use Cookies
              to enhance the performance and functionality of our website but
              are non-essential to their use. However, without these cookies,
              certain functionality like videos may become unavailable or you
              would be required to enter your login details every time you visit
              the website as we would not be able to remember that you had
              logged in previously. Most web browsers can be set to disable the
              use of Cookies. However, if you disable Cookies, you may not be
              able to access functionality on our website correctly or at all.
              We never place Personally Identifiable Information in Cookies.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Blocking and disabling cookies and similar technologies
            </SectionHeader>
            <SectionContent>
              Wherever you're located you may also set your browser to block
              cookies and similar technologies, but this action may block our
              essential cookies and prevent our website from functioning
              properly, and you may not be able to fully utilize all of its
              features and services. You should also be aware that you may also
              lose some saved information (e.g. saved login details, site
              preferences) if you block cookies on your browser. Different
              browsers make different controls available to you. Disabling a
              cookie or category of cookie does not delete the cookie from your
              browser, you will need to do this yourself from within your
              browser, you should visit your browser's help menu for more
              information.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Remarketing Services</SectionHeader>
            <SectionContent>
              We use remarketing services. What Is Remarketing? In digital
              marketing, remarketing (or retargeting) is the practice of serving
              ads across the internet to people who have already visited your
              website. It allows your company to seem like they're “following”
              people around the internet by serving ads on the websites and
              platforms they use most.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Payment Details</SectionHeader>
            <SectionContent>
              In respect to any credit card or other payment processing details
              you have provided us, we commit that this confidential information
              will be stored in the most secure manner possible.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Kids' Privacy</SectionHeader>
            <SectionContent>
              We do not address anyone under the age of 13. We do not knowingly
              collect personally identifiable information from anyone under the
              age of 13. If You are a parent or guardian and You are aware that
              Your child has provided Us with Personal Data, please contact Us.
              If We become aware that We have collected Personal Data from
              anyone under the age of 13 without verification of parental
              consent, We take steps to remove that information from Our
              servers.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Changes To Our Privacy Policy</SectionHeader>
            <SectionContent>
              We may change our Service and policies, and we may need to make
              changes to this Privacy Policy so that they accurately reflect our
              Service and policies. Unless otherwise required by law, we will
              notify you (for example, through our Service) before we make
              changes to this Privacy Policy and give you an opportunity to
              review them before they go into effect. Then, if you continue to
              use the Service, you will be bound by the updated Privacy Policy.
              If you do not want to agree to this or any updated Privacy Policy,
              you can delete your account.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Third-Party Services</SectionHeader>
            <SectionContent>
              <Box>
                We may display, include or make available third-party content
                (including data, information, applications and other products
                services) or provide links to third-party websites or services
                ("Third- Party Services").
              </Box>
              <br />
              <Box>
                You acknowledge and agree that Shopbite.co shall not be
                responsible for any Third-Party Services, including their
                accuracy, completeness, timeliness, validity, copyright
                compliance, legality, decency, quality or any other aspect
                thereof. Shopbite.co does not assume and shall not have any
                liability or responsibility to you or any other person or entity
                for any Third-Party Services.
              </Box>
              <br />
              <Box>
                Third-Party Services and links thereto are provided solely as a
                convenience to you and you access and use them entirely at your
                own risk and subject to such third parties' terms and
                conditions.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Tracking Technologies</SectionHeader>
            <SectionContent>
              <List>
                <li>
                  <Box>
                    <Text fontWeight="bold">Cookies</Text>
                    We use Cookies to enhance the performance and functionality
                    of our website but are non-essential to their use. However,
                    without these cookies, certain functionality like videos may
                    become unavailable or you would be required to enter your
                    login details every time you visit the website as we would
                    not be able to remember that you had logged in previously.
                  </Box>
                </li>
                <li>
                  <Box>
                    <Text fontWeight="bold">Local Storage</Text>
                    Local Storage sometimes known as DOM storage, provides web
                    apps with methods and protocols for storing client-side
                    data. Web storage supports persistent data storage, similar
                    to cookies but with a greatly enhanced capacity and no
                    information stored in the HTTP request header.
                  </Box>
                </li>
                <li>
                  <Box>
                    <Text fontWeight="bold">Sessions</Text>
                    Shopbite.co uses "Sessions" to identify the areas of our
                    website that you have visited. A Session is a small piece of
                    data stored on your computer or mobile device by your web
                    browser.
                  </Box>
                </li>
              </List>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Information about General Data Protection Regulation (GDPR)
            </SectionHeader>
            <SectionContent>
              We may be collecting and using information from you if you are
              from the European Economic Area (EEA), and in this section of our
              Privacy Policy we are going to explain exactly how and why is this
              data collected, and how we maintain this data under protection
              from being replicated or used in the wrong way.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>What is GDPR?</SectionHeader>
            <SectionContent>
              <Box>
                GDPR is an EU-wide privacy and data protection law that
                regulates how EU residents' data is protected by companies and
                enhances the control the EU residents have, over their personal
                data.
              </Box>
              <br />
              <Box>
                The GDPR is relevant to any globally operating company and not
                just the EU-based businesses and EU residents. Our customers’
                data is important irrespective of where they are located, which
                is why we have implemented GDPR controls as our baseline
                standard for all our operations worldwide.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>What is personal data?</SectionHeader>
            <SectionContent>
              <Box>
                Any data that relates to an identifiable or identified
                individual. GDPR covers a broad spectrum of information that
                could be used on its own, or in combination with other pieces of
                information, to identify a person. Personal data extends beyond
                a person’s name or email address. Some examples include
                financial information, political opinions, genetic data,
                biometric data, IP addresses, physical address, sexual
                orientation, and ethnicity.
              </Box>
              <br />
              <Box>
                The Data Protection Principles include requirements such as:
                <List>
                  <li>
                    Personal data collected must be processed in a fair, legal,
                    and transparent way and should only be used in a way that a
                    person would reasonably expect.
                  </li>
                  <li>
                    Personal data should only be collected to fulfil a specific
                    purpose and it should only be used for that purpose.
                    Organizations must specify why they need the personal data
                    when they collect it.
                  </li>
                  <li>
                    Personal data should be held no longer than necessary to
                    fulfil its purpose.
                  </li>
                  <li>
                    People covered by the GDPR have the right to access their
                    own personal data. They can also request a copy of their
                    data, and that their data be updated, deleted, restricted,
                    or moved to another organization.
                  </li>
                </List>
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Why is GDPR important?</SectionHeader>
            <SectionContent>
              GDPR adds some new requirements regarding how companies should
              protect individuals' personal data that they collect and process.
              It also raises the stakes for compliance by increasing enforcement
              and imposing greater fines for breach. Beyond these facts it's
              simply the right thing to do. At Shopbite.co we strongly believe
              that your data privacy is very important and we already have solid
              security and privacy practices in place that go beyond the
              requirements of this new regulation.
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              Individual Data Subject's Rights - Data Access, Portability and
              Deletion
            </SectionHeader>
            <SectionContent>
              <Box>
                We are committed to helping our customers meet the data subject
                rights requirements of GDPR. Shopbite.co processes or stores all
                personal data in fully vetted, DPA compliant vendors. We do
                store all conversation and personal data for up to 6 years
                unless your account is deleted. In which case, we dispose of all
                data in accordance with our Terms of Service and Privacy Policy,
                but we will not hold it longer than 60 days.
              </Box>
              <br />
              <Box>
                We are aware that if you are working with EU customers, you need
                to be able to provide them with the ability to access, update,
                retrieve and remove personal data. We got you! We've been set up
                as self service from the start and have always given you access
                to your data and your customers data. Our customer support team
                is here for you to answer any questions you might have about
                working with the API.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>California Residents</SectionHeader>
            <SectionContent>
              <Box>
                The California Consumer Privacy Act (CCPA) requires us to
                disclose categories of Personal Information we collect and how
                we use it, the categories of sources from whom we collect
                Personal Information, and the third parties with whom we share
                it, which we have explained above.
              </Box>
              <br />
              <Box>
                We are also required to communicate information about rights
                California residents have under California law. You may exercise
                the following rights:
                <List>
                  <li>
                    Right to Know and Access. You may submit a verifiable
                    request for information regarding the: (1) categories of
                    Personal Information we collect, use, or share; (2) purposes
                    for which categories of Personal Information are collected
                    or used by us; (3) categories of sources from which we
                    collect Personal Information; and (4) specific pieces of
                    Personal Information we have collected about you.
                  </li>
                  <li>
                    Right to Equal Service. We will not discriminate against you
                    if you exercise your privacy rights.
                  </li>
                  <li>
                    Right to Delete. You may submit a verifiable request to
                    close your account and we will delete Personal Information
                    about you that we have collected.
                  </li>
                  <li>
                    Request that a business that sells a consumer's personal
                    data, not sell the consumer's personal data.
                  </li>
                </List>
                <br />
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us. We do not sell the Personal Information of our users. For
                more information about these rights, please contact us.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>
              California Online Privacy Protection Act (CalOPPA)
            </SectionHeader>
            <SectionContent>
              <Box>
                CalOPPA requires us to disclose categories of Personal
                Information we collect and how we use it, the categories of
                sources from whom we collect Personal Information, and the third
                parties with whom we share it, which we have explained above.
              </Box>
              <br />
              <Box>
                CalOPPA users have the following rights:
                <List>
                  <li>
                    Right to Know and Access. You may submit a verifiable
                    request for information regarding the: (1) categories of
                    Personal Information we collect, use, or share; (2) purposes
                    for which categories of Personal Information are collected
                    or used by us; (3) categories of sources from which we
                    collect Personal Information; and (4) specific pieces of
                    Personal Information we have collected about you.
                  </li>
                  <li>
                    Right to Equal Service. We will not discriminate against you
                    if you exercise your privacy rights.
                  </li>
                  <li>
                    Right to Delete. You may submit a verifiable request to
                    close your account and we will delete Personal Information
                    about you that we have collected.
                  </li>
                  <li>
                    Right to request that a business that sells a consumer's
                    personal data, not sell the consumer's personal data.
                  </li>
                </List>
                <br />
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us. We do not sell the Personal Information of our users. For
                more information about these rights, please contact us.
              </Box>
            </SectionContent>
          </SectionItem>

          <SectionItem>
            <SectionHeader>Contact Us</SectionHeader>
            <SectionContent>
              Don't hesitate to contact us if you have any question or if you
              would like to make a request about your personal information we
              may hold about you via email to our team at:{' '}
              <Link as="a" href="mailto:support@shopbite.co">
                support@shopbite.co
              </Link>
            </SectionContent>
          </SectionItem>
        </Accordion>
      </Box>
    );
  };

  return (
    <>
      <Head>
        <title>Privacy Policy</title>
      </Head>
      <HeaderLogo />
      <Container maxW="container.lg" p="5">
        <VStack spacing="2" alignItems="flex-start">
          <Text fontSize="xxl" fontWeight="bold">
            Privacy Policy
          </Text>
          <Text
            fontSize={{ base: 'md', md: 'md', lg: 'lg' }}
            fontWeight="normal"
            fontFamily="source"
          >
            Last updated: 25 April 2022
          </Text>
          <Divider pb={1} />
          <Box
            fontSize={{ base: 'md', md: 'md', lg: 'lg' }}
            fontWeight="normal"
            fontFamily="source"
          >
            Shopbite.co (“we,” “our,” or “us”) is committed to protecting your
            privacy. This Privacy Policy explains how your personal information
            is collected, used, and disclosed by Shopbite.co.
            <br />
            <br />
            This Privacy Policy applies to our website, and its associated
            subdomains (collectively, our “Service”) alongside our application,
            Shopbite.co. By accessing or using our Service, you signify that you
            have read, understood, and agree to our collection, storage, use,
            and disclosure of your personal information as described in this
            Privacy Policy and our Terms of Service.
          </Box>
        </VStack>
        {renderPrivacyPolicy()}
      </Container>
    </>
  );
};

export default PrivacyPolicy;
